# 1. GUNAKAN IMAGE DASAR PHP VERSI CLI
FROM php:8.4-cli 

# 2. INSTALL DEPENDENDSI SISTEM DASAR DAN EKSTENSI PHP
RUN apt-get update && apt-get install -y libzip-dev zip unzip && docker-php-ext-install pdo pdo_mysql zip 

# 3. INSTALL COMPOSER
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer 

# 4. TETAPKAN DIREKTORI KERJA UTAMA DI DALAM CONTAINER
WORKDIR /var/www